version: "3.1"
services:
    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=*******
            - MYSQL_DATABASE=*****
            - MYSQL_USER=*****
            - MYSQL_PASSWORD=*****
        ports:
            - "****:*****"
    webserver:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ./app:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "*****:***"

    php:
        build: 
            context: phpdocker/php-fpm
            args:
                user: ******
                uid: 1000
        working_dir: /application
        volumes:
            - ./app:/application:cached
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
